spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?serverTimezone=UTC&UseSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: Petrovkm10081008
    driver-class-name: com.mysql.cj.jdbc.Driver
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
someParameter:
  value: 333

